spring:
  profiles:
    group:
      local:
        - local
        - oauth
      prod :
        - db
        - oauth
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL57Dialect
      format_sql: true
      default_batch_fetch_size: 100
    generate-ddl: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  devtools:
    livereload:
      enabled: 'true'

# server
server:
  servlet:
    encoding:
      force: 'true'
      charset: UTF-8
      enabled: 'true'
    contextPath: /
  port: '8081'
build:
  date: '@build.date@'

# log
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      apache:
        tiles: INFO
      hibernate:
        SQL: DEBUG
    root: INFO
    com:
      samsung:
        security: DEBUG
  file:
    name: ./ssafy-web.log

# jwt token
jwt:
  access-token-props:
    secret: adsjkQWFRaeiasjodfiwAWeeifjaSDOFJaiewAEWgIREAjORaerjAOESJOgDASIKFJIAJqiojuerfiAE
    expiration-time-milli-sec: '3600000'
  refresh-token-props:
    expiration-time-milli-sec: '864000000'
    secret: ZqefBscadfsGjaiADFSGaoGHdsjjsDFksjgDskdjgDjgHJmdSlzLfjbhikjaqWSogvjdsjzUEvlkvvhnDFGVnkfa==
---
# local only
spring.config.activate.on-profile: local
# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      password: idontknow
      username: idontknow
    url: jdbc:mysql://localhost:3306/idontknow?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
  # mail setting
  mail:
    host: smtp.gmail.com
    port: 587
    username: idontknowa208
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true